spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/j1809?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 19970506
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.bing.pojo